sensor:
  - platform: rotary_encoder
    name: ${dial_name}
    id: ${dial_id}
    pin_a:
      number: ${dial_pin_b}
      mode:
        input: true
        pulldown: true
    pin_b:
      number: ${dial_pin_a}
      mode:
        input: true
        pulldown: true
    resolution: 2
    publish_initial_value: true
    min_value: 0
    max_value: 9
    on_value:
      then:
        # Clear all LEDs
        - light.addressable_set:
            id: ${leds_id}
            red: 100%
            green: 100%
            blue: 100%
            color_brightness: 0%
        - delay: 20ms
        # Turn on LEDs 0 till <value>
        - light.addressable_set:
            id: ${leds_id}
            range_from: 0
            range_to: !lambda |-
              return static_cast<int>(x);
            red: 100%
            green: 100%
            blue: 100%
            color_brightness: 20%
        - delay: 5s
        - light.turn_off: ${leds_id}

light:
  - id: ${leds_id}
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin:
      number: ${leds_pin}
    num_leds: 10
    chipset: WS2812
    name: ${leds_name}
    rmt_symbols: 48
