sensor:
  - platform: rotary_encoder
    name: ${dial_name}
    id: ${dial_id}
    pin_a:
      number: ${dial_pin_b}
      mode:
        input: true
        pulldown: true
    pin_b:
      number: ${dial_pin_a}
      mode:
        input: true
        pulldown: true
    resolution: 2
    publish_initial_value: true
    min_value: 1
    max_value: 10
    on_value:
      then:
        # Turn on LEDs 1 till <value>
        - light.addressable_set:
            id: ${leds_id}
            range_from: 0
            range_to: !lambda 'return int(x - 1);'
            red: 100%
            green: 100%
            blue: 100%
            color_brightness: 20%
        # Turn off LEDs <value + 1> till 10 if value < 10
        - if:
            condition:
              lambda: 'return x < 10;'
            then:
              - light.addressable_set:
                  id: ${leds_id}
                  range_from: !lambda 'return int(x);'
                  range_to: 9
                  red: 100%
                  green: 100%
                  blue: 100%
                  color_brightness: 0%
        - delay: 5s
        - light.turn_off: ${leds_id}

light:
  - id: ${leds_id}
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin:
      number: ${leds_pin}
    num_leds: 10
    chipset: WS2812
    name: ${leds_name}
    rmt_symbols: 48
