esphome:
  name: domodulo-capsule
  friendly_name: "domodulo Capsule"
  name_add_mac_suffix: true
  project: 
    name: "domodulo.Capsule"
    version: "0.4.0" 

dashboard_import:
  package_import_url: github://domodulo/capsule-esphome/capsule.yaml
  import_full_config: true

logger:

# Wi-Fi
wifi:
  ap:
    ssid: "domodulo Capsule"

# Improv via BLE
esp32_improv:
  authorizer: none

# Improv via Serial
improv_serial:

# OTA updates via ESPHome
ota:
  - platform: esphome
    id: ota_esphome

captive_portal:

packages:
  base: !include
    file: modules/base.yaml
